# Generated by Django 4.2.6 on 2023-10-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='amount',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='outputmodel',
            name='amount',
            field=models.FloatField(max_length=20),
        ),
    ]
