# Generated by Django 4.2.5 on 2023-09-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='outputmodel',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
