# Generated by Django 4.2.5 on 2023-09-21 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_alter_inputmodel_amount_alter_outputmodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='calc.machinemodel'),
        ),
    ]
