# Generated by Django 4.2.5 on 2023-09-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_alter_recipemodel_machine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemModel',
        ),
    ]
