# Generated by Django 4.2.5 on 2023-09-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_delete_itemmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('item_img', models.ImageField(upload_to='static/images/')),
            ],
        ),
    ]
