# Generated by Django 4.2.5 on 2023-09-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_itemmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputmodel',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipemodel',
            name='machine',
        ),
        migrations.DeleteModel(
            name='InputModel',
        ),
        migrations.DeleteModel(
            name='MachineModel',
        ),
        migrations.DeleteModel(
            name='OutputModel',
        ),
        migrations.DeleteModel(
            name='RecipeModel',
        ),
    ]
