# Generated by Django 4.2.5 on 2023-09-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_machinemodel_recipemodel_outputmodel_inputmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinemodel',
            old_name='name',
            new_name='machine_name',
        ),
    ]
