# Generated by Django 4.2.5 on 2023-09-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_rename_name_machinemodel_machine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='item_img',
            field=models.ImageField(upload_to='static/images/items'),
        ),
        migrations.AlterField(
            model_name='machinemodel',
            name='machine_img',
            field=models.ImageField(upload_to='static/images/machines'),
        ),
    ]
